def menu() -> None:
	print("=========================")
	print("     Menu de opciones    ")
	print("=========================")
	print("[1] Invertir una cadena de texto")
	print("[2] Contador de palabras de un texto")
	print("[3] Formador de acronimos")
	print("[4] Par o impar")
	print("[5] Factorial")
	print("[6] Fibonacci")
	print("[7] Palindromo")
	print("[8] Salir")
	print("=========================")