def menu() -> None:
	print("=============================================")
	print("               Menú de opciones              ")
	print("=============================================")
	print("[1] Invertir una cadena de texto")
	print("[2] Contador de palabras de un texto")
	print("[3] Formador de acrónimos de una organización")
	print("[4] Par o impar")
	print("[5] Factorial")
	print("[6] Fibonacci")
	print("[7] Palindromo")
	print("[8] Salir")
	print("=============================================")